/**
 * ISO 3166-1 alpha-2 ulke kodlari + TR/EN adlari.
 * `Intl.DisplayNames` ile uretildi (elle yazilan/isabetsiz olabilecek
 * bir liste yerine); `profile.country` bu listedeki `code` degerini tutar.
 */
export const COUNTRIES = [
  { code: "AF", tr: "Afganistan", en: "Afghanistan" },
  { code: "DE", tr: "Almanya", en: "Germany" },
  { code: "US", tr: "Amerika Birleşik Devletleri", en: "United States" },
  { code: "AD", tr: "Andorra", en: "Andorra" },
  { code: "AO", tr: "Angola", en: "Angola" },
  { code: "AG", tr: "Antigua ve Barbuda", en: "Antigua & Barbuda" },
  { code: "AR", tr: "Arjantin", en: "Argentina" },
  { code: "AL", tr: "Arnavutluk", en: "Albania" },
  { code: "AU", tr: "Avustralya", en: "Australia" },
  { code: "AT", tr: "Avusturya", en: "Austria" },
  { code: "AZ", tr: "Azerbaycan", en: "Azerbaijan" },
  { code: "BS", tr: "Bahamalar", en: "Bahamas" },
  { code: "BH", tr: "Bahreyn", en: "Bahrain" },
  { code: "BD", tr: "Bangladeş", en: "Bangladesh" },
  { code: "BB", tr: "Barbados", en: "Barbados" },
  { code: "BY", tr: "Belarus", en: "Belarus" },
  { code: "BE", tr: "Belçika", en: "Belgium" },
  { code: "BZ", tr: "Belize", en: "Belize" },
  { code: "BJ", tr: "Benin", en: "Benin" },
  { code: "AE", tr: "Birleşik Arap Emirlikleri", en: "United Arab Emirates" },
  { code: "GB", tr: "Birleşik Krallık", en: "United Kingdom" },
  { code: "BO", tr: "Bolivya", en: "Bolivia" },
  { code: "BA", tr: "Bosna-Hersek", en: "Bosnia & Herzegovina" },
  { code: "BW", tr: "Botsvana", en: "Botswana" },
  { code: "BR", tr: "Brezilya", en: "Brazil" },
  { code: "BN", tr: "Brunei", en: "Brunei" },
  { code: "BG", tr: "Bulgaristan", en: "Bulgaria" },
  { code: "BF", tr: "Burkina Faso", en: "Burkina Faso" },
  { code: "BI", tr: "Burundi", en: "Burundi" },
  { code: "BT", tr: "Butan", en: "Bhutan" },
  { code: "CV", tr: "Cabo Verde", en: "Cape Verde" },
  { code: "DZ", tr: "Cezayir", en: "Algeria" },
  { code: "DJ", tr: "Cibuti", en: "Djibouti" },
  { code: "CI", tr: "Côte d’Ivoire", en: "Côte d’Ivoire" },
  { code: "TD", tr: "Çad", en: "Chad" },
  { code: "CZ", tr: "Çekya", en: "Czechia" },
  { code: "CN", tr: "Çin", en: "China" },
  { code: "DK", tr: "Danimarka", en: "Denmark" },
  { code: "DO", tr: "Dominik Cumhuriyeti", en: "Dominican Republic" },
  { code: "DM", tr: "Dominika", en: "Dominica" },
  { code: "EC", tr: "Ekvador", en: "Ecuador" },
  { code: "GQ", tr: "Ekvator Ginesi", en: "Equatorial Guinea" },
  { code: "SV", tr: "El Salvador", en: "El Salvador" },
  { code: "ID", tr: "Endonezya", en: "Indonesia" },
  { code: "ER", tr: "Eritre", en: "Eritrea" },
  { code: "AM", tr: "Ermenistan", en: "Armenia" },
  { code: "EE", tr: "Estonya", en: "Estonia" },
  { code: "SZ", tr: "Esvatini", en: "Eswatini" },
  { code: "ET", tr: "Etiyopya", en: "Ethiopia" },
  { code: "MA", tr: "Fas", en: "Morocco" },
  { code: "FJ", tr: "Fiji", en: "Fiji" },
  { code: "PH", tr: "Filipinler", en: "Philippines" },
  { code: "FI", tr: "Finlandiya", en: "Finland" },
  { code: "FR", tr: "Fransa", en: "France" },
  { code: "GA", tr: "Gabon", en: "Gabon" },
  { code: "GM", tr: "Gambiya", en: "Gambia" },
  { code: "GH", tr: "Gana", en: "Ghana" },
  { code: "GN", tr: "Gine", en: "Guinea" },
  { code: "GW", tr: "Gine-Bissau", en: "Guinea-Bissau" },
  { code: "GD", tr: "Grenada", en: "Grenada" },
  { code: "GT", tr: "Guatemala", en: "Guatemala" },
  { code: "GY", tr: "Guyana", en: "Guyana" },
  { code: "ZA", tr: "Güney Afrika", en: "South Africa" },
  { code: "KR", tr: "Güney Kore", en: "South Korea" },
  { code: "SS", tr: "Güney Sudan", en: "South Sudan" },
  { code: "GE", tr: "Gürcistan", en: "Georgia" },
  { code: "HT", tr: "Haiti", en: "Haiti" },
  { code: "HR", tr: "Hırvatistan", en: "Croatia" },
  { code: "IN", tr: "Hindistan", en: "India" },
  { code: "NL", tr: "Hollanda", en: "Netherlands" },
  { code: "HN", tr: "Honduras", en: "Honduras" },
  { code: "IQ", tr: "Irak", en: "Iraq" },
  { code: "IR", tr: "İran", en: "Iran" },
  { code: "IE", tr: "İrlanda", en: "Ireland" },
  { code: "ES", tr: "İspanya", en: "Spain" },
  { code: "IL", tr: "İsrail", en: "Israel" },
  { code: "SE", tr: "İsveç", en: "Sweden" },
  { code: "CH", tr: "İsviçre", en: "Switzerland" },
  { code: "IT", tr: "İtalya", en: "Italy" },
  { code: "IS", tr: "İzlanda", en: "Iceland" },
  { code: "JM", tr: "Jamaika", en: "Jamaica" },
  { code: "JP", tr: "Japonya", en: "Japan" },
  { code: "KH", tr: "Kamboçya", en: "Cambodia" },
  { code: "CM", tr: "Kamerun", en: "Cameroon" },
  { code: "CA", tr: "Kanada", en: "Canada" },
  { code: "ME", tr: "Karadağ", en: "Montenegro" },
  { code: "QA", tr: "Katar", en: "Qatar" },
  { code: "KZ", tr: "Kazakistan", en: "Kazakhstan" },
  { code: "KE", tr: "Kenya", en: "Kenya" },
  { code: "CY", tr: "Kıbrıs", en: "Cyprus" },
  { code: "KG", tr: "Kırgızistan", en: "Kyrgyzstan" },
  { code: "KI", tr: "Kiribati", en: "Kiribati" },
  { code: "CO", tr: "Kolombiya", en: "Colombia" },
  { code: "KM", tr: "Komorlar", en: "Comoros" },
  { code: "CG", tr: "Kongo - Brazavil", en: "Congo - Brazzaville" },
  { code: "CD", tr: "Kongo - Kinşasa", en: "Congo - Kinshasa" },
  { code: "CR", tr: "Kosta Rika", en: "Costa Rica" },
  { code: "KW", tr: "Kuveyt", en: "Kuwait" },
  { code: "KP", tr: "Kuzey Kore", en: "North Korea" },
  { code: "MK", tr: "Kuzey Makedonya", en: "North Macedonia" },
  { code: "CU", tr: "Küba", en: "Cuba" },
  { code: "LA", tr: "Laos", en: "Laos" },
  { code: "LS", tr: "Lesotho", en: "Lesotho" },
  { code: "LV", tr: "Letonya", en: "Latvia" },
  { code: "LR", tr: "Liberya", en: "Liberia" },
  { code: "LY", tr: "Libya", en: "Libya" },
  { code: "LI", tr: "Liechtenstein", en: "Liechtenstein" },
  { code: "LT", tr: "Litvanya", en: "Lithuania" },
  { code: "LB", tr: "Lübnan", en: "Lebanon" },
  { code: "LU", tr: "Lüksemburg", en: "Luxembourg" },
  { code: "HU", tr: "Macaristan", en: "Hungary" },
  { code: "MG", tr: "Madagaskar", en: "Madagascar" },
  { code: "MW", tr: "Malavi", en: "Malawi" },
  { code: "MV", tr: "Maldivler", en: "Maldives" },
  { code: "MY", tr: "Malezya", en: "Malaysia" },
  { code: "ML", tr: "Mali", en: "Mali" },
  { code: "MT", tr: "Malta", en: "Malta" },
  { code: "MH", tr: "Marshall Adaları", en: "Marshall Islands" },
  { code: "MU", tr: "Mauritius", en: "Mauritius" },
  { code: "MX", tr: "Meksika", en: "Mexico" },
  { code: "EG", tr: "Mısır", en: "Egypt" },
  { code: "FM", tr: "Mikronezya", en: "Micronesia" },
  { code: "MN", tr: "Moğolistan", en: "Mongolia" },
  { code: "MD", tr: "Moldova", en: "Moldova" },
  { code: "MC", tr: "Monako", en: "Monaco" },
  { code: "MR", tr: "Moritanya", en: "Mauritania" },
  { code: "MZ", tr: "Mozambik", en: "Mozambique" },
  { code: "MM", tr: "Myanmar (Burma)", en: "Myanmar (Burma)" },
  { code: "NA", tr: "Namibya", en: "Namibia" },
  { code: "NR", tr: "Nauru", en: "Nauru" },
  { code: "NP", tr: "Nepal", en: "Nepal" },
  { code: "NE", tr: "Nijer", en: "Niger" },
  { code: "NG", tr: "Nijerya", en: "Nigeria" },
  { code: "NI", tr: "Nikaragua", en: "Nicaragua" },
  { code: "NO", tr: "Norveç", en: "Norway" },
  { code: "CF", tr: "Orta Afrika Cumhuriyeti", en: "Central African Republic" },
  { code: "UZ", tr: "Özbekistan", en: "Uzbekistan" },
  { code: "PK", tr: "Pakistan", en: "Pakistan" },
  { code: "PW", tr: "Palau", en: "Palau" },
  { code: "PA", tr: "Panama", en: "Panama" },
  { code: "PG", tr: "Papua Yeni Gine", en: "Papua New Guinea" },
  { code: "PY", tr: "Paraguay", en: "Paraguay" },
  { code: "PE", tr: "Peru", en: "Peru" },
  { code: "PL", tr: "Polonya", en: "Poland" },
  { code: "PT", tr: "Portekiz", en: "Portugal" },
  { code: "RO", tr: "Romanya", en: "Romania" },
  { code: "RW", tr: "Ruanda", en: "Rwanda" },
  { code: "RU", tr: "Rusya", en: "Russia" },
  { code: "KN", tr: "Saint Kitts ve Nevis", en: "St. Kitts & Nevis" },
  { code: "LC", tr: "Saint Lucia", en: "St. Lucia" },
  { code: "VC", tr: "Saint Vincent ve Grenadinler", en: "St. Vincent & Grenadines" },
  { code: "WS", tr: "Samoa", en: "Samoa" },
  { code: "SM", tr: "San Marino", en: "San Marino" },
  { code: "ST", tr: "Sao Tome ve Principe", en: "São Tomé & Príncipe" },
  { code: "SN", tr: "Senegal", en: "Senegal" },
  { code: "SC", tr: "Seyşeller", en: "Seychelles" },
  { code: "RS", tr: "Sırbistan", en: "Serbia" },
  { code: "SL", tr: "Sierra Leone", en: "Sierra Leone" },
  { code: "SG", tr: "Singapur", en: "Singapore" },
  { code: "SK", tr: "Slovakya", en: "Slovakia" },
  { code: "SI", tr: "Slovenya", en: "Slovenia" },
  { code: "SB", tr: "Solomon Adaları", en: "Solomon Islands" },
  { code: "SO", tr: "Somali", en: "Somalia" },
  { code: "LK", tr: "Sri Lanka", en: "Sri Lanka" },
  { code: "SD", tr: "Sudan", en: "Sudan" },
  { code: "SR", tr: "Surinam", en: "Suriname" },
  { code: "SY", tr: "Suriye", en: "Syria" },
  { code: "SA", tr: "Suudi Arabistan", en: "Saudi Arabia" },
  { code: "CL", tr: "Şili", en: "Chile" },
  { code: "TJ", tr: "Tacikistan", en: "Tajikistan" },
  { code: "TZ", tr: "Tanzanya", en: "Tanzania" },
  { code: "TH", tr: "Tayland", en: "Thailand" },
  { code: "TW", tr: "Tayvan", en: "Taiwan" },
  { code: "TL", tr: "Timor-Leste", en: "Timor-Leste" },
  { code: "TG", tr: "Togo", en: "Togo" },
  { code: "TO", tr: "Tonga", en: "Tonga" },
  { code: "TT", tr: "Trinidad ve Tobago", en: "Trinidad & Tobago" },
  { code: "TN", tr: "Tunus", en: "Tunisia" },
  { code: "TV", tr: "Tuvalu", en: "Tuvalu" },
  { code: "TR", tr: "Türkiye", en: "Türkiye" },
  { code: "TM", tr: "Türkmenistan", en: "Turkmenistan" },
  { code: "UG", tr: "Uganda", en: "Uganda" },
  { code: "UA", tr: "Ukrayna", en: "Ukraine" },
  { code: "OM", tr: "Umman", en: "Oman" },
  { code: "UY", tr: "Uruguay", en: "Uruguay" },
  { code: "JO", tr: "Ürdün", en: "Jordan" },
  { code: "VU", tr: "Vanuatu", en: "Vanuatu" },
  { code: "VA", tr: "Vatikan", en: "Vatican City" },
  { code: "VE", tr: "Venezuela", en: "Venezuela" },
  { code: "VN", tr: "Vietnam", en: "Vietnam" },
  { code: "YE", tr: "Yemen", en: "Yemen" },
  { code: "NZ", tr: "Yeni Zelanda", en: "New Zealand" },
  { code: "GR", tr: "Yunanistan", en: "Greece" },
  { code: "ZM", tr: "Zambiya", en: "Zambia" },
  { code: "ZW", tr: "Zimbabve", en: "Zimbabwe" },
];

/**
 * @param {string} code
 * @param {string} locale
 */
export function getCountryName(code, locale) {
  const country = COUNTRIES.find((c) => c.code === code);
  if (!country) return code ?? "";
  return locale === "en" ? country.en : country.tr;
}
