-- Hemdem v2 — başlangıç şeması
-- Tüm yazma/okuma sunucu tarafından `service role` anahtarı ile yapılır.
-- RLS her tabloda açık ve hiçbir policy tanımlanmaz (varsayılan reddet) —
-- amaç, tarayıcıdan `anon key` ile doğrudan Supabase'e erişimi imkansız
-- kılmak (service role zaten RLS'i bypass eder).

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  name text,
  avatar_url text,
  bio text,
  gender text check (gender in ('male','female')),
  country text,
  interested_in text check (interested_in in ('male','female','both')),
  birthdate date,
  language text not null default 'tr',
  role text not null default 'user' check (role in ('user','admin')),
  is_banned boolean not null default false,
  gate_test_id uuid,
  gate_test_threshold smallint check (gate_test_threshold between 0 and 100),
  allow_guest_likes boolean not null default false
);

-- ---------------------------------------------------------------------
-- tests / answers
-- ---------------------------------------------------------------------
create table public.tests (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  title text not null,
  category_id smallint not null,
  language text not null default 'tr',
  questions jsonb not null,
  point bigint not null default 0,
  approved boolean not null default true,
  is_deleted boolean not null default false
);

alter table public.profiles
  add constraint profiles_gate_test_id_fkey
  foreign key (gate_test_id) references public.tests(id);

create table public.answers (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  test_id uuid not null references public.tests(id) on delete cascade,
  user_answers jsonb not null,
  unique (user_id, test_id)
);

-- ---------------------------------------------------------------------
-- swipes / matches
-- ---------------------------------------------------------------------
create table public.swipes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  from_user uuid not null references public.profiles(id) on delete cascade,
  to_user uuid not null references public.profiles(id) on delete cascade,
  action text not null check (action in ('like','dislike','superlike')),
  unique (from_user, to_user)
);

create table public.matches (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  check (user_a < user_b),
  unique (user_a, user_b)
);

-- ---------------------------------------------------------------------
-- chats / messages
-- ---------------------------------------------------------------------
create table public.chats (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  source text not null check (source in ('match','super_message')),
  check (user_a < user_b),
  unique (user_a, user_b)
);

create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  chat_id bigint not null references public.chats(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  content text not null
);

create index messages_chat_id_created_at_idx on public.messages (chat_id, created_at);

-- ---------------------------------------------------------------------
-- posts / notes
-- ---------------------------------------------------------------------
create table public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) <= 500),
  tagged_test_id uuid references public.tests(id) on delete set null
);

create index posts_created_at_idx on public.posts (created_at desc);

create table public.notes (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  text text not null
);

-- ---------------------------------------------------------------------
-- profile_views / coins / points
-- ---------------------------------------------------------------------
create table public.profile_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  viewer_id uuid not null references public.profiles(id) on delete cascade,
  viewed_id uuid not null references public.profiles(id) on delete cascade,
  unique (viewer_id, viewed_id)
);

create table public.user_coins (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  coin bigint not null default 0
);

create table public.user_points (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  point bigint not null default 0
);

-- ---------------------------------------------------------------------
-- requests (destek/şikayet)
-- ---------------------------------------------------------------------
create table public.requests (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  user_id uuid references public.profiles(id) on delete set null,
  type text not null check (type in ('complaint','request')),
  subject text not null,
  description text not null,
  email text
);

-- ---------------------------------------------------------------------
-- Atomik coin/point fonksiyonları (race condition'sız bakiye güncelleme).
-- ---------------------------------------------------------------------
create or replace function public.increment_coin(p_user_id uuid, p_amount bigint)
returns bigint
language plpgsql
as $$
declare
  v_new_balance bigint;
begin
  insert into public.user_coins (user_id, coin)
  values (p_user_id, p_amount)
  on conflict (user_id) do update set coin = public.user_coins.coin + excluded.coin
  returning coin into v_new_balance;

  return v_new_balance;
end;
$$;

create or replace function public.decrement_coin_if_sufficient(p_user_id uuid, p_amount bigint)
returns table (ok boolean, new_balance bigint)
language plpgsql
as $$
declare
  v_new_balance bigint;
begin
  update public.user_coins
  set coin = coin - p_amount
  where user_id = p_user_id and coin >= p_amount
  returning coin into v_new_balance;

  if v_new_balance is null then
    return query select false, coalesce((select coin from public.user_coins where user_id = p_user_id), 0);
  else
    return query select true, v_new_balance;
  end if;
end;
$$;

create or replace function public.increment_point(p_user_id uuid, p_amount bigint)
returns bigint
language plpgsql
as $$
declare
  v_new_balance bigint;
begin
  insert into public.user_points (user_id, point)
  values (p_user_id, p_amount)
  on conflict (user_id) do update set point = public.user_points.point + excluded.point
  returning point into v_new_balance;

  return v_new_balance;
end;
$$;

-- ---------------------------------------------------------------------
-- RLS: her tabloda açık, hiç policy yok (varsayılan reddet).
-- Sunucu tarafı `service role` key ile çalıştığı için bypass edilir.
-- ---------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.tests enable row level security;
alter table public.answers enable row level security;
alter table public.swipes enable row level security;
alter table public.matches enable row level security;
alter table public.chats enable row level security;
alter table public.messages enable row level security;
alter table public.posts enable row level security;
alter table public.notes enable row level security;
alter table public.profile_views enable row level security;
alter table public.user_coins enable row level security;
alter table public.user_points enable row level security;
alter table public.requests enable row level security;

-- ---------------------------------------------------------------------
-- Haftalık otomatik sohbet temizliği: 1 haftadır last_message_at
-- güncellenmeyen chats satırlarını (ve cascade ile messages'ı) siler.
-- pg_cron extension'ının Supabase projesinde açık olması gerekir.
-- ---------------------------------------------------------------------
create extension if not exists pg_cron;

select cron.schedule(
  'weekly-inactive-chat-cleanup',
  '0 3 * * 0',
  $$delete from public.chats where last_message_at < now() - interval '7 days'$$
);
