-- Bildirimler: testler bir uyum aracı olduğu için, bir kullanıcı bir testi
-- çözdüğünde aynı testi daha önce çözmüş ve benzer cevap vermiş kişilere
-- (ve o kişiye) karşılıklı bildirim düşer.

create table public.notifications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('test_similarity','incoming_like','match','message')),
  actor_id uuid references public.profiles(id) on delete cascade,
  test_id uuid references public.tests(id) on delete cascade,
  similarity smallint check (similarity between 0 and 100),
  is_read boolean not null default false
);

create index notifications_user_id_created_at_idx
  on public.notifications (user_id, created_at desc);

create index notifications_unread_idx
  on public.notifications (user_id)
  where is_read = false;

-- Diğer tüm tablolarla aynı strateji: RLS açık, policy yok (varsayılan
-- reddet). Uygulama her zaman service role ile sunucu tarafından yazar.
alter table public.notifications enable row level security;
