-- Engelleme + kullanıcı bazlı şikayet. Mesajlaşma/eşleşme içeren bir
-- app'te bu, App Store'un UGC/kullanıcı-kullanıcı iletişimi olan app'ler
-- için zorunlu tuttuğu (Guideline 1.2) "engelle + şikayet et" akışı —
-- kod kalitesinden önce gelen bir mağaza-onay şartı.

create table public.user_blocks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  unique (blocker_id, blocked_id)
);

create index user_blocks_blocker_id_idx on public.user_blocks (blocker_id);
create index user_blocks_blocked_id_idx on public.user_blocks (blocked_id);

-- Diğer tüm tablolarla aynı strateji: RLS açık, policy yok (varsayılan
-- reddet). Uygulama her zaman service role ile sunucu tarafından yazar.
alter table public.user_blocks enable row level security;

-- Genel destek/şikayet formunu bozmadan "bu kullanıcıyı şikayet et"
-- akışını aynı tabloya bağlar — nullable, sadece hedefli şikayetlerde dolu.
alter table public.requests
  add column target_user_id uuid references public.profiles(id) on delete set null;
